# Generated by Django 3.0.3 on 2020-03-14 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sigla')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de inicio')),
                ('descricao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='ingresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=128, verbose_name='Nome')),
                ('valor', models.FloatField(null=True)),
                ('eventos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.evento')),
            ],
        ),
        migrations.CreateModel(
            name='pessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('pessoafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_ingresso.pessoaFisica')),
                ('nome', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nome')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email')),
            ],
            bases=('app_ingresso.pessoafisica',),
        ),
        migrations.CreateModel(
            name='inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.evento')),
                ('ingressos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.ingresso')),
                ('pessoas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.pessoa')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='realizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ingresso.pessoa'),
        ),
    ]
